workflows:
  build-android:
    name: Build Android APK from subdirectory
    max_build_duration: 60
    environment:
      flutter: 3.22.1
    scripts:
      - name: Build from subdirectory
        script: |
          cd pos_system
          flutter pub get
          flutter build apk --release
    artifacts:
      - pos_system/build/app/outputs/flutter-apk/app-release.apk
