workflows:
  build-android:
    name: Android Release Build
    max_build_duration: 30
    instance_type: mac_mini
    environment:
      flutter: stable
    cache:
      cache_paths:
        - ~/.pub-cache
        - pos_system/.dart_tool/
        - pos_system/build/
    scripts:
      - name: Change to project directory
        script: cd pos_system
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Android APK (Release)
        script: flutter build apk --release
    artifacts:
      - pos_system/build/app/outputs/flutter-apk/app-release.apk
