workflows:
  flutter-build:
    name: Flutter Build APK
    max_build_duration: 15
    environment:
      flutter: "3.22.0"
      xcode: latest
      android_signing:
        - keystore_reference
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - m.iggopramulia14@gmail.com
