name: pos_system
description: "A Flutter POS system designed for restaurants and UMKM businesses"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # HTTP & Networking
  http: ^1.1.2
  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  # JSON & Serialization
  json_annotation: ^4.8.1
  equatable: ^2.0.5

  # UI & Icons
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  
  # Utilities
  uuid: ^4.2.1
  intl: ^0.19.0
  logger: ^2.0.2+1
  
  # Device Features
  permission_handler: ^11.2.0
  device_info_plus: ^10.1.0
  
  # Printing (for receipts)
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  
  # Camera & QR Code
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
